language: python

python:
  - "3.5"

notifications:
    email: false

# Install packages
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov
  - pip install .

# Add the current directory to the pythonpath so that tests can load saved files
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - py.test --cov=./

after_success:
  - codecov